name: Update Team Data

on:
  repository_dispatch:
    types: [update-team-data]

jobs:
  update-team-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch latest team data from API
        run: |
          curl -s https://afaw-beta-api.onrender.com/api/teams > teamData.json

      - name: Convert JSON to JS export
        run: |
          echo "export const teamMembers = " > src/data/teamData.js
          cat teamData.json >> src/data/teamData.js
          echo ";" >> src/data/teamData.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/data/teamData.js
          git diff --quiet || git commit -m "Update team data"
          git push
